import Link from "next/link";
import { notFound } from "next/navigation";
import { requireCatalogAdmin } from "@/lib/admin-auth";
import { getCatalogRecord, listEvidence } from "@/lib/catalog-repository";
import { addEvidence, updateCatalogApp } from "../../actions";
import "../../admin.css";

export const dynamic="force-dynamic";

export default async function CatalogAppPage({params}:{params:Promise<{id:string}>}){
  const {id}=await params; await requireCatalogAdmin(`/admin/apps/${id}`); const app=await getCatalogRecord(id); if(!app) notFound(); const evidence=await listEvidence(id);
  const checks=[{label:"Identity and description",pass:Boolean(app.name&&app.description&&app.type)},{label:"Platforms confirmed",pass:app.platforms.length>0},{label:"Pricing recorded",pass:Boolean(app.price)},{label:"AI status classified",pass:Boolean(app.ai)},{label:"Feature inventory",pass:app.features.length>0},{label:"Evidence attached",pass:evidence.length>0},{label:"Legit Score reviewed",pass:app.researchStatus==="Reviewed"}];
  const ready=checks.every(check=>check.pass);
  return <main className="admin-page standalone-admin editor-page"><div className="admin-utility"><Link href="/admin">← Research dashboard</Link><span>{app.name}</span></div><div className="editor-heading"><div><p className="eyebrow">CATALOG RECORD</p><h1>{app.name}</h1><p>Update factual fields, attach evidence, and advance the research state.</p></div><span className={ready?"gate-ready":"gate-blocked"}>{ready?"Ready to publish":"Publication blocked"}</span></div>
  <div className="editor-layout"><form action={updateCatalogApp} className="record-form"><input type="hidden" name="id" value={app.id}/><section><h2>Identity and positioning</h2><label>Name<input name="name" defaultValue={app.name} required/></label><label>Product type<input name="type" defaultValue={app.type} required/></label><label>Short description<textarea name="description" defaultValue={app.description} required rows={4}/></label><label>Primary caveat<textarea name="caveat" defaultValue={app.caveat} rows={3}/></label></section><section><h2>Access and classification</h2><div className="form-grid"><label>Price summary<input name="price" defaultValue={app.price}/></label><label>Monthly price<input name="monthlyPrice" type="number" step="0.01" defaultValue={app.monthlyPrice??""}/></label><label>Programming authorship<input name="authorship" defaultValue={app.authorship}/></label><label>AI status<select name="ai" defaultValue={app.ai}><option>No AI identified</option><option>Optional AI</option><option>AI supporting features</option><option>AI central</option></select></label><label>Research status<select name="researchStatus" defaultValue={app.researchStatus}><option>Candidate</option><option>Researching</option><option>Evaluation ready</option><option>Reviewed</option></select></label></div><label>Platforms, comma separated<input name="platforms" defaultValue={app.platforms.join(", ")}/></label><label>Goals, comma separated<input name="goals" defaultValue={app.goals.join(", ")}/></label><label>Features, comma separated<textarea name="features" defaultValue={app.features.join(", ")} rows={3}/></label><div className="check-grid"><label><input type="checkbox" name="deliversCompleteProgram" defaultChecked={app.deliversCompleteProgram}/> Complete program</label><label><input type="checkbox" name="programLibrary" defaultChecked={app.programLibrary}/> Program library</label><label><input type="checkbox" name="adaptiveProgramming" defaultChecked={app.adaptiveProgramming}/> Adaptive programming</label></div></section><button className="admin-primary" type="submit">Save catalog record</button></form>
  <aside className="editor-sidebar"><section><p className="eyebrow">PUBLISHING GATE</p><h2>{checks.filter(check=>check.pass).length} of {checks.length} checks passed</h2><ul className="gate-list">{checks.map(check=><li className={check.pass?"passed":"missing"} key={check.label}><span>{check.pass?"✓":"!"}</span>{check.label}</li>)}</ul></section><section><p className="eyebrow">ADD EVIDENCE</p><form action={addEvidence} className="evidence-form"><input type="hidden" name="appId" value={app.id}/><label>Source type<select name="sourceType"><option>Official website</option><option>Google Play</option><option>Apple App Store</option><option>Official documentation</option><option>Privacy policy</option><option>Hands-on testing</option><option>Developer correspondence</option></select></label><label>URL<input name="url" type="url" required placeholder="https://"/></label><label>Claim supported<textarea name="claim" required rows={3}/></label><label>Internal note<textarea name="note" rows={2}/></label><label className="public-check"><input type="checkbox" name="public"/> Show this source publicly</label><button className="admin-primary" type="submit">Add evidence</button></form></section></aside></div>
  <section className="evidence-list"><div><p className="eyebrow">SOURCE LOG</p><h2>{evidence.length} evidence source{evidence.length===1?"":"s"}</h2></div>{evidence.length?evidence.map(item=><article key={item.id}><div><strong>{item.source_type}</strong><span>{new Date(item.checked_at).toLocaleDateString("en-US")}</span></div><p>{item.claim_supported}</p><a href={item.url} target="_blank" rel="noreferrer">Open source ↗</a>{item.internal_note?<small>{item.internal_note}</small>:null}</article>):<p className="empty-evidence">No evidence attached yet. Add the first official source above.</p>}</section></main>
}
